[package]
name = "image-hue-rotation"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = 2
lto = true
codegen-units = 1
panic = 'abort'
strip = "symbols"

[dependencies]
clap = { version = "4.4.11", features = ["derive"] }
image = "0.24.7"
